In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sr inithya\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\sr inithya\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("MovieGenre.csv", encoding="ISO-8859-1")

In [5]:
df

,imdbId,Imdb Link,Title,IMDB Score,Genre,Poster
0,114709,http://www.imdb.com/title/tt114709,Toy Story (1995),8.3,Animation|Adventure|Comedy,https://images-na.ssl-images-amazon.com/images...
1,113497,http://www.imdb.com/title/tt113497,Jumanji (1995),6.9,Action|Adventure|Family,https://images-na.ssl-images-amazon.com/images...
2,113228,http://www.imdb.com/title/tt113228,Grumpier Old Men (1995),6.6,Comedy|Romance,https://images-na.ssl-images-amazon.com/images...
3,114885,http://www.imdb.com/title/tt114885,Waiting to Exhale (1995),5.7,Comedy|Drama|Romance,https://images-na.ssl-images-amazon.com/images...
4,113041,http://www.imdb.com/title/tt113041,Father of the Bride Part II (1995),5.9,Comedy|Family|Romance,https://images-na.ssl-images-amazon.com/images...
...,...,...,...,...,...,...
40103,83168,http://www.imdb.com/title/tt83168,Tanya's Island (1980),4.3,Drama,https://images-na.ssl-images-amazon.com/images...
40104,82875,http://www.imdb.com/title/tt82875,Pacific Banana (1981),4.7,Comedy,https://images-na.ssl-images-amazon.com/images...
40105,815258,http://www.imdb.com/title/tt815258,Werewolf in a Womens Prison (2006),4.5,Horror,https://images-na.ssl-images-amazon.com/images...
40106,79142,http://www.imdb.com/title/tt79142,Xiao zi ming da (1979),6.5,Action|Comedy,https://images-na.ssl-images-amazon.com/images...
40107,70710,http://www.imdb.com/title/tt70710,Snatched (1973),6.5,Crime|Drama|Thriller,NaN

In [6]:
df

,imdbId,Imdb Link,Title,IMDB Score,Genre,Poster
0,114709,http://www.imdb.com/title/tt114709,Toy Story (1995),8.3,Animation|Adventure|Comedy,https://images-na.ssl-images-amazon.com/images...
1,113497,http://www.imdb.com/title/tt113497,Jumanji (1995),6.9,Action|Adventure|Family,https://images-na.ssl-images-amazon.com/images...
2,113228,http://www.imdb.com/title/tt113228,Grumpier Old Men (1995),6.6,Comedy|Romance,https://images-na.ssl-images-amazon.com/images...
3,114885,http://www.imdb.com/title/tt114885,Waiting to Exhale (1995),5.7,Comedy|Drama|Romance,https://images-na.ssl-images-amazon.com/images...
4,113041,http://www.imdb.com/title/tt113041,Father of the Bride Part II (1995),5.9,Comedy|Family|Romance,https://images-na.ssl-images-amazon.com/images...
...,...,...,...,...,...,...
40103,83168,http://www.imdb.com/title/tt83168,Tanya's Island (1980),4.3,Drama,https://images-na.ssl-images-amazon.com/images...
40104,82875,http://www.imdb.com/title/tt82875,Pacific Banana (1981),4.7,Comedy,https://images-na.ssl-images-amazon.com/images...
40105,815258,http://www.imdb.com/title/tt815258,Werewolf in a Womens Prison (2006),4.5,Horror,https://images-na.ssl-images-amazon.com/images...
40106,79142,http://www.imdb.com/title/tt79142,Xiao zi ming da (1979),6.5,Action|Comedy,https://images-na.ssl-images-amazon.com/images...
40107,70710,http://www.imdb.com/title/tt70710,Snatched (1973),6.5,Crime|Drama|Thriller,NaN

In [7]:
pip install nltk

Requirement already satisfied: nltk in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\sr inithya\appdata\roaming\python\python313\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize

In [9]:
from nltk.corpus import stopwords

In [10]:
nltk.download('punkt')  
nltk.download('punkt_tab') 
nltk.download('stopwords')

[nltk_data] Downloading package punkt to C:\Users\SR
[nltk_data]     INITHYA\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\SR
[nltk_data]     INITHYA\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to C:\Users\SR
[nltk_data]     INITHYA\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [12]:
import re

In [13]:
cleaned = []

In [14]:
for text in df['Title']:  
    cleaned_text = re.sub(r'[^\w\s]', '', text) 
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text)  
    cleaned_data = cleaned_text.strip() 
    cleaned.append(cleaned_data)

In [15]:
tokens = [word_tokenize(x) for x in cleaned]

In [16]:
stop = set(stopwords.words('english'))

In [17]:
stpktn = []

In [18]:
for k in range(len(df['Title'])):  
    p = [i for i in tokens[k] if i not in stop]  
    stpktn.append(p)

In [19]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [20]:
stemed_data = []
for Text in stpktn:
  stm = [ps.stem(word) for word in Text]
  stemed_data.append(stm)

In [23]:
stemed_data

[['kicker',
  'watchlist',
  'xide',
  'tit',
  'soq',
  'pnk',
  'cpw',
  'bpz',
  'aj',
  'trade',
  'method',
  '1',
  'method',
  '2',
  'see',
  'prev',
  'post'],
 ['user',
  'aap',
  'movi',
  '55',
  'return',
  'feage',
  'indic',
  '15',
  'trade',
  'year',
  'awesom'],
 ['user',
  'id',
  'afraid',
  'short',
  'amzn',
  'look',
  'like',
  'nearmonopoli',
  'ebook',
  'infrastructureasaservic'],
 ['mnta', 'over', '1200'],
 ['oi', 'over', '2137'],
 ['pgnx', 'over', '304'],
 ['aap',
  'user',
  'current',
  'downtrend',
  'break',
  'otherwis',
  'shortterm',
  'correct',
  'medterm',
  'downtrend'],
 ['monday',
  'rel',
  'weak',
  'nyx',
  'win',
  'tie',
  'tap',
  'ice',
  'int',
  'bmc',
  'aon',
  'c',
  'chk',
  'biib'],
 ['goog', 'ower', 'trend', 'line', 'channel', 'test', 'volum', 'support'],
 ['aap', 'watch', 'tomorrow', 'ong', 'entri'],
 ['im',
  'assum',
  'fcx',
  'open',
  'tomorrow',
  '3425',
  'trigger',
  'buy',
  'still',
  'much',
  'like',
  'setup'],
 ['it',
  'realli',
  'worri',
  'everyon',
  'expect',
  'market',
  'ralli',
  'nowusu',
  'exact',
  'opposit',
  'happen',
  'everi',
  'time',
  'shall',
  'see',
  'soon',
  'bac',
  'spx',
  'jpm'],
 ['aap',
  'gamco',
  'arri',
  'haverti',
  'appl',
  'is',
  'extrem',
  'cheap',
  'great',
  'video'],
 ['user',
  'maykiljil',
  'post',
  'i',
  'agre',
  'msft',
  'go',
  'higher',
  'possibl',
  'north',
  '30'],
 ['momentum',
  'come',
  'back',
  'etfc',
  'broke',
  'ma200',
  'resist',
  'solid',
  'volum',
  'friday',
  'ong',
  'setup'],
 ['ha', 'hit', '3565', 'mean', 'resum', 'target', '42', 'level'],
 ['user',
  'gameplan',
  'shot',
  'today',
  'i',
  'like',
  'trend',
  'break',
  'may',
  'ch',
  'break',
  'oc',
  'weekli',
  'trend',
  'break',
  'back',
  'juli',
  '2011'],
 ['fcx',
  'gap',
  'well',
  'ideal',
  'entri',
  'look',
  'pull',
  'least',
  '35',
  'open',
  'entri'],
 ['user',
  'great',
  'list',
  'particularli',
  'like',
  'fisv',
  'syk',
  'all',
  'buy',
  'hold',
  'type',
  'check',
  'free',
  'list'],
 ['athx', 'upper', 'trend', 'line'],
 ['ng', 'nice', 'pnf', 'by', 'breakout', 'need', 'follow', 'thru'],
 ['wont', 'believ', 'aap', 'uptrend', 'back', 'cross', 'ma50'],
 ['x', 'swing', 'still'],
 ['swi', '30', 'float', 'short', 'break', 'ouch'],
 ['biof', 'want', '490', 'comin'],
 ['vs',
  'invert',
  'head',
  'shoulder',
  'play',
  'well',
  'wasnt',
  'abl',
  'catch',
  'entri',
  'eye'],
 ['red', 'readi', 'break'],
 ['ei', 'close', 'break', 'my', 'trigger', '3040'],
 ['user',
  'bac',
  'for',
  'quick',
  'trade',
  'latebut',
  'invest',
  '1198',
  'good',
  'entri',
  'point',
  'imho'],
 ['chdn',
  'ong',
  '4902',
  'trail',
  'stop',
  '5666',
  '6',
  'prior',
  'stop',
  '5417',
  '4988',
  '4982',
  '4547',
  '4302',
  '4192'],
 ['aap',
  'vome',
  'today',
  'impress',
  'at',
  'rate',
  'well',
  'probabl',
  'get',
  '30m',
  'share',
  'trade',
  'today'],
 ['user',
  'ad',
  'vxi',
  'long',
  'bottom',
  'today',
  'trade',
  'also',
  'got',
  'wpi',
  'near',
  'low'],
 ['i',
  'repeat',
  'global',
  'economi',
  'go',
  'get',
  'better',
  'year',
  'go',
  'c',
  'instead',
  'bac'],
 ['goog', 'go', 'ong', 'close', '725'],
 ['nkd',
  'look',
  'like',
  'good',
  'short',
  'fail',
  'break',
  'price',
  'level',
  'resist',
  '116',
  'today'],
 ['gs',
  'like',
  'price',
  'action',
  'so',
  'far',
  'hold',
  '130',
  'still',
  'decid',
  'whether',
  'go',
  'ong',
  'call',
  'stock'],
 ['sbx', 'buy', 'clear', 'resist', '545'],
 ['new',
  'target',
  'aap',
  'notic',
  'shakeout',
  'read',
  '849',
  'buy',
  'dot',
  'monday'],
 ['too',
  'earli',
  'short',
  'move',
  'stock',
  'market',
  'need',
  'day',
  'settl',
  'patienc',
  'coh',
  'bwd',
  'dt',
  'aap',
  'pay'],
 ['aap',
  'obber',
  'hit',
  'appl',
  'store',
  'pari',
  'prefer',
  'take',
  'merchendis',
  'cash',
  'bullish'],
 ['axa',
  'here',
  'tip',
  'day',
  'buy',
  'you',
  'even',
  'sign',
  'newslett',
  'anyth',
  'o',
  'if',
  'im',
  'wrong',
  'i',
  'eat',
  'crow'],
 ['x',
  '12',
  'due',
  'move',
  'today',
  'kirbi',
  'daili',
  'around',
  '2600',
  'still',
  'swing',
  '12'],
 ['aap',
  '10',
  'min',
  'short',
  'long',
  'fulli',
  'ad',
  'look',
  'pop',
  'marketshakeout',
  'reset'],
 ['ng',
  'stellar',
  'move',
  'still',
  'long',
  'swing',
  'full',
  'posit',
  'i',
  'believ',
  'user',
  'user',
  '2'],
 ['atic', 'tade', 'setp', 'ko', 'an', 'cnx'],
 ['idcc',
  '50sma',
  'act',
  'good',
  'support',
  'shortterm',
  'momentum',
  'indic',
  'switch',
  'upsid'],
 ['new',
  'post',
  'bac',
  'is',
  'at',
  '19',
  'month',
  'high',
  'but',
  'show',
  'sign',
  'stress'],
 ['c', 'two', 'daili', 'bull', 'flag', 'top', 'otherbullish', 'still'],
 ['ng',
  'tradit',
  'at',
  'point',
  'figur',
  'bullish',
  'by',
  'signal',
  'multiyear',
  'high'],
 ['jpm',
  'closed10sma',
  'mondayu',
  'know',
  'ruleslarg',
  'cup',
  'n',
  'handlestil',
  'bullish'],
 ['eog',
  'ascend',
  'triangl',
  'origin',
  'target',
  '127',
  'extens',
  'ep',
  'feb',
  '11th',
  '12',
  'posit',
  'swing'],
 ['aapl',
  'daili',
  'broke',
  'downtrendfrom',
  'close',
  'price',
  'w',
  'v',
  'pattern',
  'back',
  'play600',
  'target'],
 ['phm',
  'pultegroup',
  'option',
  'bear',
  'bet',
  '15',
  'million',
  '11',
  'move',
  'april'],
 ['bac', 'in', '1197', 'trade'],
 ['short',
  'setup',
  'display',
  'rel',
  'weak',
  'ao',
  'coh',
  'pay',
  'bwd',
  'dt',
  'shd',
  'wtw',
  'p',
  'prepar',
  'short',
  'stall',
  'es_f'],
 ['when',
  'amzn',
  'monet',
  'electron',
  'make',
  'traffic',
  'marketplac',
  'aap',
  'goog',
  'wake',
  'say',
  'didnt',
  'buy',
  'ebay'],
 ['cvi',
  'start',
  'clean',
  'book',
  'make',
  'first',
  'buy',
  'yr',
  'entri',
  '4954',
  'stop',
  '4743'],
 ['sam',
  'cheer',
  'temporari',
  'solut',
  'econom',
  'woe',
  'entri',
  '13981',
  'stop',
  '13192'],
 ['sk', 'gave'],
 ['ovti',
  'ttm',
  'end',
  'oct',
  '2012',
  'neg',
  '151',
  'million',
  'oper',
  'cash',
  'flow',
  '273',
  'declin',
  'vs',
  'yoy',
  'ttm',
  'end',
  'oct',
  '2011'],
 ['aap', 'goog', 'respond', 'posit', 'good', 'jobless', 'claim', 'number'],
 ['analyst',
  'price',
  'target',
  'earn',
  'target',
  'come',
  'downexacti',
  'want',
  'see',
  'prior',
  'aap',
  'report'],
 ['user', 'nice', 'color', 'intc', 'bull', 'well'],
 ['head',
  'p',
  'aa',
  'earn',
  '1813',
  'ess',
  'than',
  'week',
  'away',
  'tho',
  'the',
  'season',
  'doesnt',
  'eay',
  'begin',
  'crank',
  'til',
  '116',
  'w',
  'gs',
  'jpm',
  'ebay',
  'et',
  'al'],
 ['trade',
  'idea',
  'buy',
  'wo',
  'market',
  '2664',
  'target',
  '36',
  'cut',
  '2350'],
 ['trade', 'idea', 'buy', 'dc', 'market', '5850', 'target', '67', 'cut', '53'],
 ['goog', 'look', 'set', 'make', 'new', 'ath', 'now', 'e', 'unknown'],
 ['goog', 'trade', 'one', 'long', 'vers', '10sma'],
 ['fnf',
  'ong',
  '1943',
  'trail',
  'stop',
  '2104',
  '6',
  'prior',
  'stop',
  '1971',
  '1952',
  '1870',
  '1865',
  '1807',
  '1787'],
 ['fod',
  'see',
  'solid',
  'move',
  'tom',
  'system',
  'predict',
  'nice',
  'green',
  'candl'],
 ['thi',
  'year',
  'fit',
  'health',
  'appsth',
  'winner',
  'gynorm',
  'specul',
  'run',
  'high',
  'nke'],
 ['it', 'time', 'invest', 'msft', 'compq'],
 ['new',
  'post',
  'short',
  'will',
  'make',
  'dime',
  'ong',
  'will',
  'make',
  'dollar',
  'aap',
  'spx',
  'qqq',
  'p'],
 ['nbeliev',
  'payment',
  'trend',
  'vc',
  'chase',
  'easili',
  'play',
  'public',
  'market',
  'ebay',
  'v',
  'mastercard',
  'ma',
  'time',
  'high'],
 ['some',
  'watch',
  'list',
  'stock',
  'trigger',
  'today',
  'oex',
  'agnx',
  'tv',
  'vbd',
  'xide',
  'ppc',
  'exp',
  'onti',
  'bmn',
  'fs',
  'wk',
  'chmt',
  'fbc',
  'isi',
  'aig'],
 ['nice', 'bull', 'flag', 'breakout', 'oc', 'technolog', 'softwar'],
 ['my',
  'setup',
  'alert',
  'went',
  'bonker',
  'todayon',
  'mani',
  'got',
  'triggeredcuphandl',
  'breakout',
  'pfe'],
 ['the',
  'host',
  'mostcongrat',
  'cloud',
  'today',
  'ax',
  'user',
  'alltim',
  'high',
  'wow'],
 ['x', 'did', 's', 'steel', 'just', 'breakout', 'mt'],
 ['dndn',
  'broken',
  'clear',
  '55',
  'resistanc',
  'level',
  'heavi',
  'volum',
  'could',
  'head',
  'much',
  'higher'],
 ['exp', 'look', 'good', 'higher', 'price'],
 ['apc', 'weekli', 'set', 'long'],
 ['i',
  'go',
  'morn',
  'long',
  '3',
  'aap',
  '560',
  'call',
  'option',
  'goog',
  '725',
  'call',
  'jan',
  '4th',
  'expir'],
 ['es_f',
  'path',
  'higher',
  'unthreaten',
  'unless',
  '145225',
  'support',
  'fail',
  'see',
  'resist',
  '146600',
  'spx',
  'stock'],
 ['monitor',
  's',
  'linepric',
  'dynam',
  'stock',
  'close',
  'dec28',
  's',
  'line',
  'new',
  'high',
  'be4',
  'price',
  'mho',
  'tsm',
  'ipgp',
  'eqix',
  'bc',
  'bdc',
  'ash'],
 ['ddd', 'idcc', 'continu', 'higher'],
 ['had',
  'hope',
  'pick',
  'ost',
  'today',
  'look',
  'like',
  'im',
  'day',
  'late',
  'nice',
  'move',
  'morn'],
 ['gp', 'wow', 'wa', 'fast', 'fast', 'fade'],
 ['amzn',
  'go',
  '260',
  'should',
  'go',
  'near',
  '300',
  'market',
  'behav',
  'week'],
 ['huston', 'geen', 'aap'],
 ['p', 'long', '955'],
 ['hn', 'breakoutbut', '3rd', 'day', 'look', 'pullback', 'enter', 'long'],
 ['ng',
  'ascend',
  'triangl',
  'much',
  'like',
  'fs',
  'x',
  'breakout',
  '127',
  'exten',
  '1618',
  'target',
  'fib',
  'subject'],
 ['kcg', 'thing', 'make', 'go', 'hmmmm'],
 ['vng', 'huge', 'news', 'patent', 'attorney', 'dan', 'avich'],
 ['ng', 'nhod', 'check', 'weekli', 'target', 'previou', 'low', '2006'],
 ['ng', 'nhod', 'see', 'check', 'weekli', 'target', 'previou', 'low', '2006'],
 ['aig',
  'american',
  'intern',
  'group',
  'option',
  'trader',
  'bet',
  '4',
  'move',
  'next',
  'friday'],
 ['p', 'balanc', '32'],
 ['vng', 'buy', 'vs', 'sell'],
 ['bac',
  'in',
  '1200',
  'sinc',
  'consolid',
  'level',
  'we',
  'could',
  'close',
  '1209',
  'market',
  'stabl',
  'pm',
  'imho'],
 ['vng', 'parabol', 'move', 'comin'],
 ['new',
  'soni',
  'preown',
  'block',
  'tech',
  'patent',
  'unearth',
  'sne',
  '50',
  'gme',
  'profit',
  'pre',
  'own',
  'last',
  'one',
  'turn',
  'light'],
 ['like',
  'vs',
  'love',
  'wynn',
  '111',
  'entri',
  'new',
  'target',
  'yesterday',
  '121',
  'nice'],
 ['user',
  'spx',
  '146490',
  'wave',
  'iv',
  'would',
  '20',
  'point',
  'lower',
  '146700',
  'key',
  'es_f',
  'hod',
  '146000',
  'necklin',
  '145850',
  'bearish'],
 ['ddd',
  'consolid',
  'strong',
  'move',
  'previou',
  'day',
  '55',
  '60',
  'next',
  'buy',
  'point',
  '60',
  'volum',
  'hold'],
 ['vng',
  '12',
  'mil',
  'share',
  'short',
  'plu',
  'long',
  'buy',
  'massiv',
  'vng',
  'short',
  'squeez',
  'just',
  'thought',
  'stori',
  'dead',
  'avich',
  'kill',
  'short',
  'thesi'],
 ['wow', 'good', 'bk', 't', 'user', 'sale', 'nook', '13', 'holiday'],
 ['ac',
  'watch',
  'list',
  'volum',
  'pick',
  '139',
  'full',
  'day',
  'averag',
  '200day',
  'bounc'],
 ['the',
  'new',
  'wightwatch',
  'ad',
  'fun',
  'light',
  'regular',
  'peopl',
  'interest',
  'i',
  'still',
  'dont',
  'trust',
  'wtw',
  'posit'],
 ['amzn',
  'hold',
  'well',
  'next',
  'buy',
  'point',
  'clear',
  'upper',
  'trend',
  'line',
  'heavi',
  'volum'],
 ['ma',
  'exactli',
  'want',
  'see',
  'follow',
  'thru',
  'day',
  'break',
  'new',
  'high',
  'volum'],
 ['zc', 'user', 'there', 'buy'],
 ['aap', 'spi', 'qe', '2013', 'now', 'bring', 'geithner'],
 ['over',
  'extend',
  'stock',
  'market',
  'unexpect',
  'news',
  'fed',
  'minut',
  'down',
  'esd',
  'panicki',
  'es_f',
  'nq_f'],
 ['spi',
  'ncle',
  'ben',
  'need',
  'spice',
  'thing',
  'littl',
  'aap',
  'peopl',
  'bore',
  'wake'],
 ['aap',
  'might',
  'close',
  'low',
  'day',
  'bear',
  'control',
  'descend',
  'trendlin',
  'watch'],
 ['fan', 'seek', '200d', 'im', 'ad', 'synthet', 'short', 'add', '200d'],
 ['cwst',
  'low',
  'day',
  '450',
  'near',
  'high',
  'day',
  '456',
  'watchn',
  'bout',
  'minim',
  'risk'],
 ['all', 'gme', 'gamestop', 'short', 'target', 'spi'],
 ['time', 'get', 'cloud', 'stock', 'vmw', 'cm'],
 ['bac', 'keep', 'overniight', 'mmi', 'po', 'bin', 'premarket', 'tmorrow'],
 ['polk',
  'expect',
  '2013',
  's',
  'new',
  'vehicl',
  'egistr',
  '153',
  'million',
  'polk',
  'f',
  'gm',
  'i',
  'think',
  'low'],
 ['veri',
  'bullish',
  'market',
  'also',
  'talk',
  'trend',
  'scti',
  'ost',
  'angi',
  'fio',
  'panw',
  'a',
  'jcp',
  'p',
  'yep',
  'mnst',
  'gpn',
  'show'],
 ['bac', 'happen', 'next'],
 ['kcg', 'someon', 'bought', '322k', '4', 'jan', '18', 'call'],
 ['man',
  'i',
  'didnt',
  'know',
  'skippi',
  'i',
  'made',
  'thiswould',
  'thrown',
  'jar',
  'h',
  'hormel'],
 ['big',
  'move',
  'bond',
  'today',
  '7',
  'month',
  'high',
  '10',
  'rate',
  'still',
  'go',
  'lower',
  'zn_f',
  'could',
  'get',
  'truli',
  'ugli',
  'good',
  'nfp',
  'number',
  'am',
  'spi',
  'tt'],
 ['market',
  'wrap',
  'video',
  'addit',
  'watch',
  'ist',
  'includ',
  'bcei',
  'bji',
  'cee',
  'es',
  'son',
  'sqnm',
  'nx',
  'yep'],
 ['mayb',
  'vrng',
  'ask',
  'judg',
  '7',
  'royalti',
  'becam',
  'riski',
  'goog',
  'deal',
  'want',
  'settl'],
 ['bji', 'over', '3553', 'good', 'volum'],
 ['cee', 'over', '3512'],
 ['sqnm', 'over', '505'],
 ['nx', 'on', 'flag', 'break'],
 ['3d',
  'system',
  'bring',
  'nextgen',
  'consum',
  '3d',
  'print',
  'ce',
  '2013',
  'ddd'],
 ['aap',
  'top',
  'april',
  'aston',
  'kutcher',
  'star',
  'job',
  'kinda',
  'like',
  'facebook',
  'social',
  'network',
  'came',
  'fb'],
 ['vng',
  'w',
  'macd',
  'turn',
  'signal',
  'line',
  'vng',
  'could',
  'post',
  'nice',
  'ralli',
  'current',
  'level'],
 ['pi',
  '3q',
  '10q',
  'oper',
  'cash',
  'flow',
  '9mo',
  '20million',
  '269declin',
  'vs',
  '9mo',
  'year',
  'ago'],
 ['bbbi',
  '3q',
  '10q',
  'oper',
  'cash',
  'flow',
  '135',
  'million',
  '53',
  'increas',
  'vs',
  'year',
  'ago',
  'q3',
  '64',
  'improv',
  'q',
  'q'],
 ['di',
  '6mo',
  'oper',
  'cash',
  'flow',
  '267',
  'million',
  'increas',
  '187',
  'million',
  'vs6mo',
  'year',
  'ago',
  '233',
  'increas'],
 ['am',
  '3q',
  '10q',
  '9mo',
  'oper',
  'cash',
  'flow',
  '32',
  'million',
  'vs',
  'neg',
  '26',
  'mil',
  '9mo',
  'year',
  'ago'],
 ['3q',
  'oper',
  'cash',
  'flow',
  'neg',
  '16',
  'million',
  'vs',
  'year',
  'ago',
  '3q',
  'neg',
  '68million',
  '52',
  'million',
  'improv'],
 ['a',
  'quiet',
  'carl',
  'icahn',
  'bullish',
  'nfx',
  'short',
  'paranoid',
  'everi',
  'close',
  'get',
  'acquir',
  'think',
  'aapl',
  'msft',
  'amzn',
  'fb'],
 ['i', 'aapl', 'bull', 'break', 'trend', 'line', 'obv'],
 ['user',
  'phantom7',
  'ive',
  'call',
  '4',
  'ever',
  'sinc',
  'start',
  'thing',
  '375',
  'given',
  'kcg'],
 ['nx',
  'watch',
  'list',
  'small',
  'flag',
  'volum',
  '26',
  'ave',
  'full',
  'day',
  'good',
  'volum'],
 ['goog',
  'pois',
  'clear',
  'next',
  'resist',
  'buy',
  'add',
  'area',
  'watch',
  'action',
  'volum',
  'close'],
 ['gdp',
  'watch',
  'list',
  'slightli',
  'line',
  '50day',
  'ema',
  'light',
  'volum',
  '5',
  'ave',
  'full',
  'day'],
 ['took', 'profit', 'ddd', 'add', 'break', '60', 'volum'],
 ['chk',
  'im',
  'look',
  'small',
  'risk',
  'posit',
  'call',
  'scalp',
  'mayb',
  'swing',
  'xe',
  'watch'],
 ['onti',
  'if',
  'holder',
  'would',
  'hold',
  'rais',
  'ask',
  'could',
  'realli',
  'pop',
  'go',
  'climb',
  'slowli',
  'regardless'],
 ['eog', 'pxd', 'oa', 'energyswag'],
 ['aap',
  'move',
  'volum',
  'couldnt',
  'cope',
  'descend',
  'trend',
  'line',
  'trend',
  'still',
  'perhap',
  '460',
  'imposs'],
 ['aap',
  '50ema',
  'continu',
  'work',
  'aap',
  'make',
  'lower',
  'high',
  'maco',
  'sens'],
 ['went',
  'short',
  'spi',
  'yesterday',
  'pick',
  'aap',
  'instead',
  'still',
  'think',
  'market',
  'need',
  'move',
  'bit',
  'resum',
  'move',
  'upsid'],
 ['aap',
  'peopl',
  'realist',
  'market',
  'undecid',
  'appl',
  'earn',
  'lift',
  'cloud',
  'if',
  'good',
  'might',
  'eay',
  'see',
  'revers'],
 ['will',
  'watch',
  'close',
  'care',
  'decid',
  'whether',
  'ong',
  'shot',
  'aap',
  'below',
  '530',
  'shot'],
 ['jcp',
  'keep',
  'eye',
  'triangl',
  'big',
  'short',
  'int',
  '34',
  'report',
  'feb',
  '27',
  'cup',
  'handl',
  'dt',
  'ong'],
 ['sold', 'littl', 'goog', 'first', 'time'],
 ['nice', 'cup', 'handl', 'breakout', 'mca'],
 ['faf', 'new', 'high'],
 ['spi', 'give', 'aap', 'finger', 'we', 'dont', 'care', 'anymor', 'lol'],
 ['the', 'smithcorona', 'ok', 'amzn'],
 ['va',
  'ong',
  '4307',
  'trail',
  'stop',
  '5898',
  '11',
  'stop',
  '5453',
  '5245',
  '4805',
  '4732',
  '4671',
  '4132',
  '3957'],
 ['amzn',
  'alert',
  'updat',
  'last',
  'minut',
  'push',
  'tri',
  'shake',
  'put',
  'hang'],
 ['aap', 'volum', 'higher', 'today', 'monday', 'keep', 'mind'],
 ['hba',
  'ong',
  '7367',
  'trail',
  'stop',
  '7192',
  '3',
  'prior',
  'stop',
  '7086',
  '6864',
  '6241'],
 ['the',
  'key',
  'panic',
  'aap',
  'domain',
  'twitchi',
  'day',
  'trader',
  'robot',
  'long',
  'term',
  'hold',
  'fundament'],
 ['nvda', '4', 'hour', 'love', 'see', 'vol', 'explod'],
 ['vng',
  'take',
  'hard',
  'look',
  'goog',
  'ftc',
  'settlement',
  'patent',
  'ftc',
  'make',
  'goog',
  'play',
  'nice',
  'vng',
  'make',
  'sens'],
 ['worri',
  'i',
  'gone',
  'oco',
  '73771',
  'call',
  'goog',
  'door',
  'step',
  'nearli',
  '40',
  'move'],
 ['vng', 'crazi', 'anyon', 'listen', 'trade', 'tool'],
 ['goog', 'get', 'fuel', 'aap', 'revers'],
 ['user',
  'make',
  'bbi',
  'offer',
  'shave',
  '4',
  'offer',
  'price',
  'bid',
  'went',
  '2426',
  '20',
  'matter',
  'month'],
 ['nvda',
  'answer',
  'question',
  'entri',
  'add',
  'red',
  'candl',
  '1050am',
  'today',
  'ove',
  'flag'],
 ['aap',
  '950',
  'lot',
  'bid',
  'feb',
  '580',
  'call',
  '950',
  'might',
  'push',
  'stock',
  'creat',
  'support',
  '26',
  'delta',
  'option'],
 ['wpi',
  'short',
  'candid',
  'list',
  '1231',
  'miss',
  'got',
  'start',
  'short',
  'today'],
 ['mye', 'break'],
 ['short',
  'ht',
  '200',
  'sma',
  'stop',
  'high',
  'day',
  'first',
  'target',
  '5395',
  'second',
  'target',
  '5321',
  'gap',
  'fill'],
 ['qcom',
  'introduc',
  'streamboost',
  'averag',
  'home',
  'connect',
  'seven',
  'devic',
  'internet'],
 ['nvda',
  'love',
  'see',
  'momo',
  'next',
  'week',
  'like',
  'previou',
  'histogram',
  'bar',
  'note'],
 ['hma',
  'unusu',
  'option',
  'activ',
  'trader',
  'buy',
  '11k',
  'jan',
  '9',
  'put',
  'short',
  'term',
  'bear',
  'play'],
 ['adb',
  'option',
  'trader',
  'buy',
  '5300',
  'feb',
  '39c',
  'oi',
  '741',
  'bet',
  'stock',
  '39',
  'feb',
  '16th'],
 ['nvda',
  'ook',
  'bullish',
  'must',
  'stay',
  '1305',
  'close',
  'basi',
  'monthli',
  'ep',
  'say'],
 ['sqnm', 'watch', 'list', 'line', 'volum', '86', 'ave', 'full', 'day'],
 ['hott', 'fail', 'breakout'],
 ['zn_f', 'tick', 'id', 'seller', 'sdjpi', 'i', 'werent', 'alreadi'],
 ['ino', 'wow', 'nice', 'accumul', 'today', 'heavi'],
 ['znga',
  'fat',
  'juici',
  'short',
  'back',
  'lower',
  'level',
  'close',
  'gap',
  '272'],
 ['gdot', 'nice', 'bounc', '50sma', 'ook', 'readi', 'test', 'recent', 'high'],
 ['hma', 'ook', '10', 'head', 'higher'],
 ['spf', 'ook', '9s', 'head', 'higher', 'lower', 'rate'],
 ['gs', 'jpm', 'xf', 'hod', 'hungri', 'stock', 'spi'],
 ['chk', 'weekli', 'bullish', 'engulf'],
 ['gs', 'look', 'good', 'head', 'next', 'week'],
 ['aap',
  'know',
  'ipad',
  'mini',
  'stock',
  'everywher',
  'go',
  '8',
  'differ',
  'store',
  'none',

In [21]:
stm=[" ".join(i) for i in stemed_data]

In [22]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.2.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.15.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [24]:
cv=CountVectorizer(max_features=2000)

In [25]:
vc=cv.fit(stm)

In [26]:
import pickle
with open("vectorizer.pickle","wb") as vcfile:
    pickle.dump(vc,vcfile)

In [27]:
x=vc.transform(stm).toarray()

In [28]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(40108, 2000))

In [29]:
y=df["Genre"]

In [30]:
from sklearn.naive_bayes import MultinomialNB

In [31]:
mb=MultinomialNB()

In [33]:
import pickle
with open("model.pickle","wb") as model_file:
    pickle.dump(mb,model_file)